# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: eshop_development
  username: postgres
  password: root
  pool: 100

development:
  <<: *default
  database: foosball_development

#production:
#  <<: *default
#  database: foosball_production
